// Header generated by cpctelera for ArkosTracker 3
enum
{
	CHANNEL_A,
	CHANNEL_B,
	CHANNEL_C
};

// Arkos player functions
void PLY_AKG_INIT(void* songdata, u16 subSong) __z88dk_callee;
void PLY_AKG_PLAY(void);
void PLY_AKG_STOP(void);
void PLY_AKG_INITSOUNDEFFECTS(void* sfx_song_data) __z88dk_fastcall;
void PLY_AKG_PLAYSOUNDEFFECT(u8 sfx_num, u8 channel, u16 volume) __z88dk_callee;
void PLY_AKG_STOPSOUNDEFFECTFROMCHANNEL(u8 channel) __z88dk_fastcall;

// Defines for cpctelera
#define cpct_PLY_AKG_Init(SONG, SSONG) PLY_AKG_INIT(SONG, SSONG)
#define cpct_PLY_AKG_Play() PLY_AKG_PLAY()
#define cpct_PLY_AKG_Stop() PLY_AKG_STOP()
#define cpct_PLY_AKG_InitSoundEffects(SFX) PLY_AKG_INITSOUNDEFFECTS(SFX)
#define cpct_PLY_AKG_PlaySoundEffect(SFX, CHAN, VOL) PLY_AKG_PLAYSOUNDEFFECT(SFX, CHAN, VOL)
#define cpct_PLY_AKG_StopSoundEffectFromChannel(CHAN) PLY_AKG_STOPSOUNDEFFECTFROMCHANNEL(CHAN)

// Track
extern u8 MUSICSTART[];

// Track
extern u8 EFFECTSSOUNDEFFECTS[];