#!/bin/bash
##-----------------------------LICENSE NOTICE------------------------------------
##  This file is part of CPCtelera: An Amstrad CPC Game Engine 
##  Copyright (C) 2016 ronaldo / Fremos / Cheesetea / ByteRealms (@FranGallegoBR)
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU Lesser General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU Lesser General Public License for more details.
##
##  You should have received a copy of the GNU Lesser General Public License
##  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##------------------------------------------------------------------------------

###########################################################################
## CPCTELERA ENGINE
###########################################################################

##
## File: cpct_aks2c
##
##    Converts an Arkos Tracker (aks) music file into an absolutely located
## data array to be compiled directly into a binary program.
##
## Usage:
##    <cpct_aks2c> [options] [aksfile]
##
## Requisites:
##    This scripts uses ArkosTracker utility by Targhan to convert an aks 
## file into a data Array or assembly files.
##
## Description:
##    This script converts an Arkos Tracker (aks) file containing music and or
## sound effects into two source code files (.s/.h) with definition and declaration
## of an array containing all music data. The data array will be absolutely located
## in memory at the desired memory address.
##      Generated binary data will be placed at specific location in memory.
##
## Command line options:
##    -gb  | --generate-bin           - Generates a binary array (Default: no). Using this switch overrides generation defaults.
##    -gf | --generate-bin-file       - Generates a binary file with song's data (Default: no). Using this switch overrides generation defaults.
##    -gs  | --generate-asm           - Generates an assembly file with song's data (Default: yes). Using this switch overrides generation defaults.
##    -h   | --help                   - Shows help information on the terminal.
##    -id  | --c-identifier [ident]   - Sets the identifier that will be used to access the array from C programs.
##    -m   | --memory-address         - Set the memory base address where song binary data will be located.
##    -o   | --output-filename        - Set the basename for output filenames (name without extension)
##    -od  | --output-directory [dir] - Sets directory where .s/.h files will be written to.
##

## Bash Include files
source $(dirname $0)/lib/bash_library.sh

## AKS2BIN utility location
ARKOS_VERSION=3
AKSPATH=${CPCT_PATH}/tools/ArkosTracker-${ARKOS_VERSION}
AKS2AKM=${AKSPATH}/tools/SongToAkm.exe
AKS2AKG=${AKSPATH}/tools/SongToAkg.exe
AKS2AKX=${AKSPATH}/tools/SongToSoundEffects.exe
AKSPROFIL=SDCC_Z80.xml
AKSPROFILPATH=${AKSPATH}/cpctelera/${AKSPROFIL}

## Configuration Variables
MEMADDR=
C_IDENTIFIER="g_music"
OUTPUT_FILENAME=
OUTPUTDIR=.
GENERATE_S=0
GENERATE_BIN=0
PLAYER=akg

## Show how this script is to be used and exit
##
function usage() {
cat <<UsageHereDoc
${COLOR_LIGHT_YELLOW}USAGE${COLOR_LIGHT_BLUE}
   $(basename $0) [options] <aksfile>
   ${COLOR_CYAN}
   Converts an Arkos Tracker (aks) music file into an absolutely located \
data array to be compiled directly into a binary program.
${COLOR_LIGHT_YELLOW}
Requisites:${COLOR_CYAN}
   This scripts uses AKSToBIN.exe utility by Targhan to convert an aks file \
into a data array. AKSToBIN.exe is included in Arkos Tracker 1.0, which is \
included into CPCtelera. AKSToBIN.exe works natively on Windows systems but \
requires mono to be installed under Linux or Mac OSX Systems.
   ${COLOR_LIGHT_YELLOW}
Description:${COLOR_CYAN}
   This script converts an Arkos Tracker (aks) file containing music and or \
sound effects into two source code files (.s/.h) with definition and declaration \
of am array containing all music data. The data array will be absolutely located \
in memory at the desired memory address.
   By default, generated binary data will be placed at location 0x100 in memory. \
You can change that location using -m modifier.
   ${COLOR_LIGHT_YELLOW}
OPTIONS
   ${COLOR_LIGHT_BLUE}
   -bl  | --bytes-per-line [bytes] ${COLOR_CYAN}
         Set the number of bytes that every generated line will contain in the .s file \
   ${COLOR_LIGHT_BLUE}
   -h   | --help ${COLOR_CYAN}
         Shows help information on the terminal \
   ${COLOR_LIGHT_BLUE}
   -gf  | --generate-bin-file ${COLOR_CYAN}
         Generates a binary file with song's data (Default: no). Using this switch overrides generation defaults \
    ${COLOR_LIGHT_BLUE}
   -gb  | --generate-bin ${COLOR_CYAN}
         Generates a binary array with song's data (Default: no). Using this switch overrides generation defaults \
   ${COLOR_LIGHT_BLUE}
   -gs  | --generate-asm ${COLOR_CYAN}
         Generates an assembly file with song's data (Default: yes). Using this switch overrides generation defaults. \
   ${COLOR_LIGHT_BLUE}
   -id  | --c-identifier [ident] ${COLOR_CYAN}
         Sets the identifier that will be used to access the array from C programs \
   -m   | --memory-address ${COLOR_CYAN}
         Set the memory base address where song binary data will be located \
   ${COLOR_LIGHT_BLUE}
   -o   | --output-filename ${COLOR_CYAN}
         Set the basename for output filenames (name without extension) \
   ${COLOR_LIGHT_BLUE}
   -od  | --output-directory [dir] ${COLOR_CYAN}
         Sets directory where .s/.h files will be written to \
   ${COLOR_NORMAL}

UsageHereDoc
   exit 1
}

##############################################################
###############################################################
## Check command line parameters
##

if (( $# < 1 )); then
   usage
fi

while (( $# >= 1 )); do
   case $1 in
      ## Show Help
      "-h" | "--help")
         usage
      ;;
      ## Select generation of binary array
      "-gb" | "--generate-bin")
         GENERATE_BIN=1
      ;;
      ## Select generation of binary file
      "-gf" | "--generate-bin-file")
         GENERATE_BIN_FILE=1         
      ;;
      ## Select generation of assembly file
      "-gs" | "--generate-asm")
         GENERATE_S=1
      ;;
      ## Set the C-identifier for the array with the generated data     
      "-id" | "--c-identifier")
         
         ## If not binary file export
         if (( GENERATE_BIN_FILE == 0 )); then
             ## Must be a valid C-identifier
             if isEmpty "$2"; then
                paramError "Parameter -id (--c-identifier) must be followed by a valid C-identifier." 4
             elif ! checkValidCIdentifier "$2"; then
                paramError "'$2' is not a valid C-identifier for -id (--c-identifier)." 5
            fi
         fi

         C_IDENTIFIER="$2"
         shift
      ;;    
      ## Set the number of bytes that everty converted line from the .s will have
      "-m" | "--memory-address")

         ## Must be an integer greater or equal than 1
         if isEmpty "$2"; then
            paramError "Parameter -m (--memory-address) must be followed by a memory address." 24
         elif ! isCIntValue "$2"; then
            paramError "'$2' is not a valid integer memory address for -m (--memory-address). " 25
         fi

         ## Check memory address is inside 64K Boundaries
         MD=$(any2Dec "$2")
         if (( MD < 0 || MD > 65535 )); then
            paramError "'$2' memory address is outside 64K boundaries (0 to 65535). " 26
         fi

         MEMADDR="$2"
         shift
      ;;
      ## Set the basename for output files
      "-o" | "--output-filename")

         ## A filename is required
         if isEmpty "$2"; then
            paramError "Parameter -o (--output-filename) must be followed by the name of the file." 27
         fi

         OUTPUT_FILENAME="$2"
         shift
      ;;
      ## Set the output directory to where .s/.h files will be written
      "-od" | "--output-directory")
         
         ## Must be a valid, existing directory
         if isEmpty "$2"; then
            paramError "Parameter -od (--output-directory) must be followed by a valid directory." 10
         elif [ ! -d "$2" ]; then
            paramError "'$2' does not exist or is not a valid directory for -od (--output-directory)." 11
         elif [ ! -r "$2" -o ! -w "$2" ]; then
            paramError "User has no read+write permission in directory '$2'." 12
         fi

         OUTPUTDIR="$2"
         shift
      ;;
       ## ArkosPlayer
      "-player" | "--player")
         PLAYER="$2"
         shift
      ;;
      ## Get main parameter (filename)
      *)
         if isCommandLineOption "$1"; then
            paramError "Unrecognized command line option '$1'" 10
         elif ! isEmpty "$FILE"; then
            paramError "Unrecognized parameter '$1'. Have you already provided a <filename> parameter?" 11
         else
            EnsureExists file "$1"
         fi

         FILE="$1"
      ;;
   esac
   shift
done

## If no file generation has been selected, resort to defaults (.h and .s)
if (( GENERATE_S == 0 && GENERATE_BIN == 0 && GENERATE_BIN_FILE == 0 )); then
   GENERATE_S=1
   GENERATE_BIN=0
   GENERATE_BIN_FILE=0
fi

## File parameter must have been passed (not empty)
if isEmpty "$FILE"; then
   paramError "A <filename> parameter is required." 12
fi

## Memory address parameter is required for binary export
if (( GENERATE_BIN == 1 )); then
    if isEmpty "$MEMADDR"; then
        paramError "Memory address parameter is required for binary export." 12
    fi
fi

## Calculate output filenames and routes
if isEmpty "$OUTPUT_FILENAME"; then
   SFILE="${OUTPUTDIR}/$(filenameWithNoExt "$(basename $FILE)").s"
   HFILE="${OUTPUTDIR}/$(filenameWithNoExt "$(basename $FILE)").h"
   BINFILE="${OUTPUTDIR}/$(filenameWithNoExt "$(basename $FILE)").bin"
   CFILE="${OUTPUTDIR}/$(filenameWithNoExt "$(basename $FILE)").c"
else
   SFILE="${OUTPUTDIR}/${OUTPUT_FILENAME}.s"
   HFILE="${OUTPUTDIR}/${OUTPUT_FILENAME}.h"
   BINFILE="${OUTPUTDIR}/${OUTPUT_FILENAME}.bin"
   CFILE="${OUTPUTDIR}/${OUTPUT_FILENAME}.c"
fi

if checkSystem cygwin; then
   ## Calculate windows valid paths for input files
   FILE_CP=`cygpath -w $FILE`
else
   ## Paths for input files are already valid under *nix
   FILE_CP=$FILE
fi

###############################################################
###############################################################
## Convert music and sounds
##

cp $AKSPROFILPATH .

echo ${COLOR_LIGHT_YELLOW}


if [ "$PLAYER" == "akm" ]; then
    checkExecutableExists "$AKS2AKM"
    
    if (( GENERATE_BIN == 1 )); then
        printf "AKM Converting '$FILE' music to Bin at ${MEMADDR}...\r\n"    
        $AKS2AKM $FILE_CP $BINFILE -bin --sourceProfile z80 -adr $MEMADDR     
		
        printf "// Generated by CPCTelera for ArkosPlayer3\n#include <cpctelera.h>\nCPCT_ABSOLUTE_LOCATION_AREA(0x%X); // Array at 0x%X \n\n" $((${MEMADDR}-1)) $((${MEMADDR})) > $CFILE
        cpct_bin2c $BINFILE -an g_${C_IDENTIFIER} >> $CFILE
        printf "CPCT_RELOCATABLE_AREA();" >> $CFILE        
        rm $BINFILE
        
        printf "// Generated by CPCTelera for ArkosPlayer3\nextern u8 g_${C_IDENTIFIER}[];" > ${HFILE}
        
    elif (( GENERATE_BIN_FILE == 1)); then
        printf "AKM Converting '$FILE' music to Binary file at ${MEMADDR}...\r\n"    
        $AKS2AKM $FILE_CP $BINFILE -bin --sourceProfile z80 -adr $MEMADDR        
        
    else        
        printf "AKM Converting '$FILE' music to Asm...\r\n"
    
        $AKS2AKM $FILE_CP $SFILE --labelPrefix ${C_IDENTIFIER} --customSourceProfileFile $AKSPROFIL
        sed -i "s/${C_IDENTIFIER}Start:/_${C_IDENTIFIER}Start::/g" $SFILE
        
        #Fix SDCC/ASZ80 format
        sed -i "s/$ +/. +/g" $SFILE
        sed -i "s/#/0x/g" $SFILE        
        printf "// Generated by CPCTelera for ArkosPlayer3\nextern u8 ${C_IDENTIFIER}Start[];" > ${HFILE}
    fi    
elif [ "$PLAYER" == "akg" ]; then    
    checkExecutableExists "$AKS2AKG"

    if (( GENERATE_BIN == 1 )); then
        printf "AKG Converting '$FILE' music to Bin at ${MEMADDR}...\r\n"
        $AKS2AKG $FILE_CP $BINFILE -bin --sourceProfile z80 -adr $MEMADDR
               
        printf "// Generated by CPCTelera for ArkosPlayer3\n#include <cpctelera.h>\nCPCT_ABSOLUTE_LOCATION_AREA(0x%X); // Array at 0x%X \n\n" $((${MEMADDR}-1)) $((${MEMADDR})) > $CFILE
        cpct_bin2c $BINFILE -an g_${C_IDENTIFIER} >> $CFILE
        printf "CPCT_RELOCATABLE_AREA();" >> $CFILE        
        rm $BINFILE

        printf "// Generated by CPCTelera for ArkosPlayer3\nextern u8 g_${C_IDENTIFIER}[];" > ${HFILE}
        
    elif (( GENERATE_BIN_FILE == 1)); then
        printf "AKG Converting '$FILE' music to Binary file at ${MEMADDR}...\r\n"
        $AKS2AKG $FILE_CP $BINFILE -bin --sourceProfile z80 -adr $MEMADDR
    
    else                
        printf "AKG Converting '$FILE' music to Asm...\r\n"
    
        $AKS2AKG $FILE_CP $SFILE --labelPrefix ${C_IDENTIFIER} --customSourceProfileFile $AKSPROFIL
        sed -i "s/${C_IDENTIFIER}Start:/_${C_IDENTIFIER}Start::/g" $SFILE
        		
        printf "// Generated by CPCTelera for ArkosPlayer3\nextern u8 ${C_IDENTIFIER}Start[];" > ${HFILE}
    fi    
elif [ "$PLAYER" == "fx" ]; then    
    checkExecutableExists "$AKS2AKX"

    if (( GENERATE_BIN == 1 )); then    
        printf "AKX Converting '$FILE' sounds to Bin at ${MEMADDR}...\r\n"
        $AKS2AKX $FILE_CP $BINFILE -bin --sourceProfile z80 -adr $MEMADDR
        
        printf "// Generated by CPCTelera for ArkosPlayer3\n#include <cpctelera.h>\nCPCT_ABSOLUTE_LOCATION_AREA(0x%X); // Array at 0x%X \n\n" $((${MEMADDR}-1)) $((${MEMADDR})) > $CFILE
        cpct_bin2c $BINFILE -an g_${C_IDENTIFIER} >> $CFILE
        printf "CPCT_RELOCATABLE_AREA();" >> $CFILE        
        rm $BINFILE

        printf "extern u8 g_${C_IDENTIFIER}[];" >> ${HFILE}
    
    elif (( GENERATE_BIN_FILE == 1)); then
        printf "AKX Converting '$FILE' sounds to Binary file at ${MEMADDR}...\r\n"
        $AKS2AKX $FILE_CP $BINFILE -bin --sourceProfile z80 -adr $MEMADDR
        
    else    
        printf "AKX Converting '$FILE' sounds to Asm...\r\n"
    
        $AKS2AKX $FILE_CP $SFILE --labelPrefix ${C_IDENTIFIER} --customSourceProfileFile $AKSPROFIL
        sed -i "s/${C_IDENTIFIER}SoundEffects:/_${C_IDENTIFIER}SoundEffects::/g" $SFILE
        printf "// Generated by CPCTelera for ArkosPlayer3\nextern u8 ${C_IDENTIFIER}SoundEffects[];" > ${HFILE}
    fi
    
fi
echo ${COLOR_NORMAL}

rm $AKSPROFIL