#!/bin/bash
##-----------------------------LICENSE NOTICE------------------------------------
##  This file is part of CPCtelera: An Amstrad CPC Game Engine 
##  Copyright (C) 2016 ronaldo / Fremos / Cheesetea / ByteRealms (@FranGallegoBR)
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU Lesser General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU Lesser General Public License for more details.
##
##  You should have received a copy of the GNU Lesser General Public License
##  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##------------------------------------------------------------------------------

###########################################################################
## CPCTELERA ENGINE
###########################################################################

##
## File: cpct_aks2c
##
##    Converts an Arkos Tracker (aks) music file into an absolutely located
## data array to be compiled directly into a binary program.
##
## Usage:
##    <cpct_aks2c> [options] [aksfile]
##
## Requisites:
##    This scripts uses AKSToBIN.exe utility by Targhan to convert an aks
## file into a data Array. AKSToBIN.exe is included in Arkos Tracker 1.0, which
## is included into CPCtelera. AKSToBIN.exe works natively on Windows systems
## but requires mono to be installed under Linux or Mac OSX Systems.
##
## Description:
##    This script converts an Arkos Tracker (aks) file containing music and or
## sound effects into two source code files (.s/.h) with definition and declaration
## of am array containing all music data. The data array will be absolutely located
## in memory at the desired memory address.
##	  By default, generated binary data will be placed at location 0x100 in memory.
## You can change that location using -m modifier.
##
##
## Command line options:
##    -bl  | --bytes-per-line [bytes] - Set the number of bytes that every generated line will contain in the .s file
##    -gb  | --generate-bin           - Generates a binary file with song's data (Default: no). Using this switch overrides generation defaults.
##    -gs  | --generate-asm           - Generates an assembly file with song's data (Default: yes). Using this switch overrides generation defaults.
##    -h   | --help                   - Shows help information on the terminal.
##    -id  | --c-identifier [ident]   - Sets the identifier that will be used to access the array from C programs.
##    -m   | --memory-address         - Set the memory base address where song binary data will be located.
##    -o   | --output-filename        - Set the basename for output filenames (name without extension)
##    -od  | --output-directory [dir] - Sets directory where .s/.h files will be written to.
##

## Bash Include files
source $(dirname $0)/lib/bash_library.sh

## AKS2BIN utility location
ARKOS_VERSION=3.5.1a
AKSPATH=${CPCT_PATH}/tools/arkosTracker-${ARKOS_VERSION}
AKS2AKM=${AKSPATH}/tools/SongToAkm
AKS2AKG=${AKSPATH}/tools/SongToAkg
AKS2AKX=${AKSPATH}/tools/SongToSoundEffects
RASM=${AKSPATH}/cpctelera/tools/rasm_w32
DISARK=${AKSPATH}/cpctelera/tools/Disark
PLAYER_AKG=${AKSPATH}/cpctelera/playerAkg
PLAYER_AKM=${AKSPATH}/cpctelera/playerAkm

## Configuration Variables
FILETYPE=aks
MEMADDR=0x100
C_IDENTIFIER="g_music"
BINTMP=$(createTempFile)
BYTESPERLINE=16
OUTPUT_FILENAME=
OUTPUTDIR=.
GENERATE_S=0
GENERATE_BIN=0
SFILE=music.s
BINFILE=music.bin
COMPILE=
PLAYER=

## Show how this script is to be used and exit
##
function usage() {
cat <<UsageHereDoc
${COLOR_LIGHT_YELLOW}USAGE${COLOR_LIGHT_BLUE}
   $(basename $0) [options] <aksfile>
   ${COLOR_CYAN}
   Converts an Arkos Tracker (aks) music file into an absolutely located \
data array to be compiled directly into a binary program.
${COLOR_LIGHT_YELLOW}
Requisites:${COLOR_CYAN}
   This scripts uses AKSToBIN.exe utility by Targhan to convert an aks file \
into a data array. AKSToBIN.exe is included in Arkos Tracker 1.0, which is \
included into CPCtelera. AKSToBIN.exe works natively on Windows systems but \
requires mono to be installed under Linux or Mac OSX Systems.
   ${COLOR_LIGHT_YELLOW}
Description:${COLOR_CYAN}
   This script converts an Arkos Tracker (aks) file containing music and or \
sound effects into two source code files (.s/.h) with definition and declaration \
of am array containing all music data. The data array will be absolutely located \
in memory at the desired memory address.
   By default, generated binary data will be placed at location 0x100 in memory. \
You can change that location using -m modifier.
   ${COLOR_LIGHT_YELLOW}
OPTIONS
   ${COLOR_LIGHT_BLUE}
   -bl  | --bytes-per-line [bytes] ${COLOR_CYAN}
         Set the number of bytes that every generated line will contain in the .s file \
   ${COLOR_LIGHT_BLUE}
   -h   | --help ${COLOR_CYAN}
         Shows help information on the terminal \
   ${COLOR_LIGHT_BLUE}
   -gb  | --generate-bin ${COLOR_CYAN}
         Generates a binary file with song's data (Default: no). Using this switch overrides generation defaults \
   ${COLOR_LIGHT_BLUE}
   -gs  | --generate-asm ${COLOR_CYAN}
         Generates an assembly file with song's data (Default: yes). Using this switch overrides generation defaults. \
   ${COLOR_LIGHT_BLUE}
   -m   | --memory-address ${COLOR_CYAN}
         Set the memory base address where song binary data will be located \
   ${COLOR_LIGHT_BLUE}
   -o   | --output-filename ${COLOR_CYAN}
         Set the basename for output filenames (name without extension) \
   ${COLOR_LIGHT_BLUE}
   -od  | --output-directory [dir] ${COLOR_CYAN}
         Sets directory where .s/.h files will be written to \
   ${COLOR_NORMAL}

UsageHereDoc
   exit 1
}

##############################################################
###############################################################
## Check command line parameters
##

if (( $# < 1 )); then
   usage
fi

while (( $# >= 1 )); do
   case $1 in
      ## Set the number of bytes that everty converted line from the .s will have
      "-bl" | "--bytes-per-line")
         
         ## Must be an integer greater or equal than 1
         if isEmpty "$2"; then
            paramError "Parameter -bl (--bytes-per-line) must be followed by an integer." 20
         elif ! isInt "$2"; then
            paramError "'$2' is not an integer. -bl (--bytes-per-line) requires and integer." 21
         elif (( $2 < 1 )); then
            paramError "'$2' is lower than 1. -bl (--bytes-per-line) requires an integer greater or equal than 1." 22
         fi          

         BYTESPERLINE="$2"
         shift
      ;;
      ## Show Help
      "-h" | "--help")
         usage
      ;;
      ## Select generation of binary file
      "-gb" | "--generate-bin")
         GENERATE_BIN=1
      ;;
      ## Select generation of assembly file
      "-gs" | "--generate-asm")
         GENERATE_S=1
      ;;
      ## Set the C-identifier for the array with the generated data     
      "-id" | "--c-identifier")
         
         ## Must be a valid C-identifier
         if isEmpty "$2"; then
            paramError "Parameter -id (--c-identifier) must be followed by a valid C-identifier." 4
         elif ! checkValidCIdentifier "$2"; then
            paramError "'$2' is not a valid C-identifier for -id (--c-identifier)." 5
         fi

         C_IDENTIFIER="$2"
         shift
      ;;    
      ## Set the number of bytes that everty converted line from the .s will have
      "-m" | "--memory-address")

         ## Must be an integer greater or equal than 1
         if isEmpty "$2"; then
            paramError "Parameter -m (--memory-address) must be followed by a memory address." 24
         elif ! isCIntValue "$2"; then
            paramError "'$2' is not a valid integer memory address for -m (--memory-address). " 25
         fi

         ## Check memory address is inside 64K Boundaries
         MD=$(any2Dec "$2")
         if (( MD < 0 || MD > 65535 )); then
            paramError "'$2' memory address is outside 64K boundaries (0 to 65535). " 26
         fi

         MEMADDR="$2"
         shift
      ;;
      ## Set the basename for output files
      "-o" | "--output-filename")

         ## A filename is required
         if isEmpty "$2"; then
            paramError "Parameter -o (--output-filename) must be followed by the name of the file." 27
         fi

         OUTPUT_FILENAME="$2"
         shift
      ;;
      ## Set the output directory to where .s/.h files will be written
      "-od" | "--output-directory")
         
         ## Must be a valid, existing directory
         if isEmpty "$2"; then
            paramError "Parameter -od (--output-directory) must be followed by a valid directory." 10
         elif [ ! -d "$2" ]; then
            paramError "'$2' does not exist or is not a valid directory for -od (--output-directory)." 11
         elif [ ! -r "$2" -o ! -w "$2" ]; then
            paramError "User has no read+write permission in directory '$2'." 12
         fi

         OUTPUTDIR="$2"
         shift
      ;;
      ## Compile
      "-compile" | "--compile")
	     COMPILE=1
      ;;
	   ## ArkosPlayer
      "-player" | "--player")
	     PLAYER="$2"
		 shift
      ;;
      ## Get main parameter (filename)
      *)
         if isCommandLineOption "$1"; then
            paramError "Unrecognized command line option '$1'" 10
         elif ! isEmpty "$FILE"; then
            paramError "Unrecognized parameter '$1'. Have you already provided a <filename> parameter?" 11
         else
            EnsureExists file "$1"
         fi

         FILE="$1"
      ;;
   esac
   shift
done

## If no file generation has been selected, resort to defaults (.h and .s)
if (( GENERATE_S == 0 && GENERATE_H == 0 && GENERATE_BIN == 0 && GENERATE_H_S == 0 )); then
   GENERATE_S=1
   GENERATE_H=1
fi

## File parameter must have been passed (not empty)
if isEmpty "$FILE"; then
   paramError "A <filename> parameter is required." 12
fi


## Calculate output filenames and routes
if isEmpty "$OUTPUT_FILENAME"; then
   SFILE="${OUTPUTDIR}/$(filenameWithNoExt "$(basename $FILE)").s"
   HFILE="${OUTPUTDIR}/$(filenameWithNoExt "$(basename $FILE)").h"
   HSFILE="${OUTPUTDIR}/$(filenameWithNoExt "$(basename $FILE)").h.s"
   BINFILE="${OUTPUTDIR}/$(filenameWithNoExt "$(basename $FILE)").bin"
else
   SFILE="${OUTPUTDIR}/${OUTPUT_FILENAME}.s"
   HFILE="${OUTPUTDIR}/${OUTPUT_FILENAME}.h"
   HSFILE="${OUTPUTDIR}/${OUTPUT_FILENAME}.h.s"
   BINFILE="${OUTPUTDIR}/${OUTPUT_FILENAME}.bin"
fi

## Check AKSToBin and Wine if Required
checkExecutableExists "$AKS2AKM"
checkExecutableExists "$AKS2AKG"
checkExecutableExists "$AKS2AKX"
checkExecutableExists "$RASM"
checkExecutableExists "$DISARK"

echo
if checkSystem cygwin; then
   ## Calculate windows valid paths for input files
   FILE_CP=`cygpath -w $FILE`
else
   EnsureCommandAvailable mono "mono has not been found on the system, \
and it's required for this script to work. Please, install mono or \
check the installation and run this script again."
   AKS2AKM="mono $AKS2AKM"
   AKS2AKG="mono $AKS2AKG"
   AKS2AKX="mono $AKS2AKX"
   RASM="mono $RASM"
   DISARK="mono $DISARK"

   ## Paths for input files are already valid under *nix
   FILE_CP=$FILE
fi

###############################################################
###############################################################
## Convert music
##

## STEP 1: Convert AKS file to ASM
printf "Converting '$FILE' to Asm..."

THEAKSFILE=$FILE_CP

if [ ! -d temp ]; then
	mkdir temp

	printf "// Header generated by cpctelera for ArkosTracker 3\nenum\n{\n\tCHANNEL_A,\n\tCHANNEL_B,\n\tCHANNEL_C\n};\n" > "${OUTPUTDIR}/arkosPlayer3.h";
	printf "; Asm generated by cpctelera for ArkosTracker 3\nPLY_AKG_HARDWARE_CPC = 1\n" > "temp/compileAt3.asm";
fi

if [ "$PLAYER" == "akm" ]; then
	
	if [ ! -d temp//PlayerAkm.asm ]; then
		cp "${PLAYER_AKM}/PlayerAkm.asm" temp
		cp "${PLAYER_AKM}/PlayerAkm_SoundEffects.asm" temp
		
ARKOSPLAYER_HEADER="
// Arkos player functions
void PLY_AKM_INIT(void* songdata, u16 subSong) __z88dk_callee;
void PLY_AKM_PLAY(void);
void PLY_AKM_STOP(void);
void PLY_AKM_INITSOUNDEFFECTS(void* sfx_song_data) __z88dk_fastcall;
void PLY_AKM_PLAYSOUNDEFFECT(u8 sfx_num, u8 channel, u16 volume) __z88dk_callee;
void PLY_AKM_STOPSOUNDEFFECTFROMCHANNEL(u8 channel) __z88dk_fastcall;

// Defines for cpctelera
#define cpct_PLY_AKM_Init(SONG, SSONG) PLY_AKM_INIT(SONG, SSONG)
#define cpct_PLY_AKM_Play() PLY_AKM_PLAY()
#define cpct_PLY_AKM_Stop() PLY_AKM_STOP()
#define cpct_PLY_AKM_InitSoundEffects(SFX) PLY_AKM_INITSOUNDEFFECTS(SFX)
#define cpct_PLY_AKM_PlaySoundEffect(SFX, CHAN, VOL) PLY_AKM_PLAYSOUNDEFFECT(SFX, CHAN, VOL)
#define cpct_PLY_AKM_StopSoundEffectFromChannel(CHAN) PLY_AKM_STOPSOUNDEFFECTFROMCHANNEL(CHAN)"

		printf "${ARKOSPLAYER_HEADER}" >> "${OUTPUTDIR}/arkosPlayer3.h";		
	fi
	
	$AKS2AKM "$THEAKSFILE" "temp/${C_IDENTIFIER}.asm" --labelPrefix ${C_IDENTIFIER} --exportPlayerConfig 
	printf "include \"${C_IDENTIFIER}.asm\"\ninclude \"${C_IDENTIFIER}_playerconfig.asm\"\n" >> "temp/compileAt3.asm"

elif [ "$PLAYER" == "akg" ]; then	

	if [ ! -d temp/PlayerAkg.asm ]; then
		cp "${PLAYER_AKG}/PlayerAkg.asm" temp
		cp "${PLAYER_AKG}/PlayerAkg_SoundEffects.asm" temp

		ARKOSPLAYER_HEADER="
// Arkos player functions
void PLY_AKG_INIT(void* songdata, u16 subSong) __z88dk_callee;
void PLY_AKG_PLAY(void);
void PLY_AKG_STOP(void);
void PLY_AKG_INITSOUNDEFFECTS(void* sfx_song_data) __z88dk_fastcall;
void PLY_AKG_PLAYSOUNDEFFECT(u8 sfx_num, u8 channel, u16 volume) __z88dk_callee;
void PLY_AKG_STOPSOUNDEFFECTFROMCHANNEL(u8 channel) __z88dk_fastcall;

// Defines for cpctelera
#define cpct_PLY_AKG_Init(SONG, SSONG) PLY_AKG_INIT(SONG, SSONG)
#define cpct_PLY_AKG_Play() PLY_AKG_PLAY()
#define cpct_PLY_AKG_Stop() PLY_AKG_STOP()
#define cpct_PLY_AKG_InitSoundEffects(SFX) PLY_AKG_INITSOUNDEFFECTS(SFX)
#define cpct_PLY_AKG_PlaySoundEffect(SFX, CHAN, VOL) PLY_AKG_PLAYSOUNDEFFECT(SFX, CHAN, VOL)
#define cpct_PLY_AKG_StopSoundEffectFromChannel(CHAN) PLY_AKG_STOPSOUNDEFFECTFROMCHANNEL(CHAN)"

		printf "${ARKOSPLAYER_HEADER}" >> "${OUTPUTDIR}/arkosPlayer3.h";
	fi

	$AKS2AKG "$THEAKSFILE" "temp/${C_IDENTIFIER}.asm" --labelPrefix ${C_IDENTIFIER} --exportPlayerConfig 
	printf "include \"${C_IDENTIFIER}.asm\"\ninclude \"${C_IDENTIFIER}_playerconfig.asm\"\n" >> "temp/compileAt3.asm"	
	
elif [ "$PLAYER" == "fx" ]; then	
	$AKS2AKX "$THEAKSFILE" "temp/${C_IDENTIFIER}.asm" --labelPrefix ${C_IDENTIFIER} 
	
	if [ -f temp/PlayerAkm.asm ]; then
		printf "\nPLY_AKM_MANAGE_SOUND_EFFECTS = 1\n" >> "temp/compileAt3.asm";
	fi
	
	if [ -f temp/PlayerAkg.asm ]; then
		printf "\nPLY_AKG_MANAGE_SOUND_EFFECTS = 1\n" >> "temp/compileAt3.asm";
	fi
	
	printf "include \"${C_IDENTIFIER}.asm\"\n" >> "temp/compileAt3.asm"
fi

if [ "$PLAYER" == "fx" ]; then
	printf "\n\n// Track\nextern u8 ${C_IDENTIFIER^^}SOUNDEFFECTS[];" >> "${OUTPUTDIR}/arkosPlayer3.h";
elif [ "$PLAYER" == "akg" ]; then
	printf "\n\n// Track\nextern u8 ${C_IDENTIFIER^^}START[];" >> "${OUTPUTDIR}/arkosPlayer3.h";
else
	printf "\n\n// Track\nextern u8 ${C_IDENTIFIER^^}[];" >> "${OUTPUTDIR}/arkosPlayer3.h";
fi

## STEP 3: Generate ArkosTracker 3 Player and Songs to assembly code 
if (( COMPILE == 1 )); then
	if [ -f temp/PlayerAkm.asm ]; then
		printf "\ninclude \"PlayerAkm.asm\"\n" >> "temp/compileAt3.asm"
		
		$RASM "temp\compileAt3.asm" -o "temp\UniversalAt3Files" -s -sl -sq > /dev/null 2>&1
		$DISARK "temp\UniversalAt3Files.bin" "${OUTPUTDIR}\playerAkmCpctelera.s" --symbolFile "temp\UniversalAt3Files.sym" --sourceProfile sdcc > /dev/null 2>&1
		
		echo -e "\n\033[32mArkosTracker ${ARKOS_VERSION} Akm Player is ready to use.\033[0m\n"
	fi
	if [ -f temp/PlayerAkg.asm ]; then
		printf "\ninclude \"PlayerAkg.asm\"\n" >> "temp/compileAt3.asm"
	
		$RASM "temp\compileAt3.asm" -o "temp\UniversalAt3Files" -s -sl -sq > /dev/null 2>&1
		$DISARK "temp\UniversalAt3Files.bin" "${OUTPUTDIR}\playerAkgCpctelera.s" --symbolFile "temp\UniversalAt3Files.sym" --sourceProfile sdcc > /dev/null 2>&1
		
		echo -e "\n\033[32mArkosTracker ${ARKOS_VERSION} Akg Player is ready to use.\033[0m\n"
	fi

	rm temp -r	
fi
