; Events generated by Arkos Tracker 3.

MainEvents
MainEventsDisarkGenerateExternalLabel

MainDisarkByteRegionStart0
    dw 97    ; Wait for 96 frames.
    db 2

    dw 18    ; Wait for 17 frames.
    db 2

    dw 18    ; Wait for 17 frames.
    db 2

    dw 18    ; Wait for 17 frames.
    db 2

    dw 18    ; Wait for 17 frames.
    db 3

    dw 6    ; Wait for 5 frames.
    db 3

    dw 12    ; Wait for 11 frames.
    db 3

    dw 6    ; Wait for 5 frames.
    db 0

MainEvents_Loop
    dw 1    ; Wait for 0 frames.
    db 2

    dw 18    ; Wait for 17 frames.
    db 2

    dw 6    ; Wait for 5 frames.
    db 3

    dw 12    ; Wait for 11 frames.
    db 2

    dw 12    ; Wait for 11 frames.
    db 2

    dw 6    ; Wait for 5 frames.
    db 3

    dw 6    ; Wait for 5 frames.
    db 2

    dw 12    ; Wait for 11 frames.
    db 3

    dw 24    ; Wait for 23 frames.
    db 2

    dw 18    ; Wait for 17 frames.
    db 2

    dw 6    ; Wait for 5 frames.
    db 3

    dw 12    ; Wait for 11 frames.
    db 2

    dw 12    ; Wait for 11 frames.
    db 2

    dw 6    ; Wait for 5 frames.
    db 2

    dw 12    ; Wait for 11 frames.
    db 2

    dw 6    ; Wait for 5 frames.
    db 3

    dw 6    ; Wait for 5 frames.
    db 3

    dw 6    ; Wait for 5 frames.
    db 3

    dw 6    ; Wait for 5 frames.
    db 3

    dw 6    ; Wait for 5 frames.
    db 0

    dw 0    ; End of sequence.
MainDisarkWordForceReference1
    dw MainEvents_Loop    ; Loops here.
MainDisarkByteRegionEnd0
