; Song Digitest, in AKY version 1.0, generated by Arkos Tracker 3.

MainSubsong0
MainSubsong0DisarkGenerateExternalLabel

; Header
MainSubsong0DisarkByteRegionStart0
    db 128    ; Format version: 0 and endianness: little-endian.
    db 3    ; How many channels are encoded.
; Frequency of the PSG index 0: 1000000Hz.
    db 64
    db 66
    db 15
    db 0
MainSubsong0DisarkByteRegionEnd0

MainSubsong0_Linker
MainSubsong0DisarkPointerRegionStart1
; Position 0
MainSubsong0DisarkWordForceNonReference2
    dw 192    ; Duration in frames.
    dw MainSubsong0_Track_3
    dw MainSubsong0_Track_1
    dw MainSubsong0_Track_2

; Position 1
MainSubsong0_LinkerLoop
; Loops here.
MainSubsong0DisarkWordForceNonReference3
    dw 192    ; Duration in frames.
    dw MainSubsong0_Track_3
    dw MainSubsong0_Track_4
    dw MainSubsong0_Track_5

MainSubsong0DisarkWordForceNonReference4
    dw 0    ; Loops (duration = 0).
    dw MainSubsong0_LinkerLoop
MainSubsong0DisarkPointerRegionEnd1

; The tracks.
MainSubsong0_Track_1
MainSubsong0DisarkByteRegionStart5
    db 96    ; Duration.
MainSubsong0DisarkByteRegionEnd5
MainSubsong0DisarkPointerRegionStart6
    dw MainSubsong0_RegisterBlock_0
MainSubsong0DisarkPointerRegionEnd6

MainSubsong0DisarkByteRegionStart7
    db 96    ; Duration.
MainSubsong0DisarkByteRegionEnd7
MainSubsong0DisarkPointerRegionStart8
    dw MainSubsong0_RegisterBlock_1
MainSubsong0DisarkPointerRegionEnd8

MainSubsong0_Track_2
MainSubsong0DisarkByteRegionStart9
    db 48    ; Duration.
MainSubsong0DisarkByteRegionEnd9
MainSubsong0DisarkPointerRegionStart10
    dw MainSubsong0_RegisterBlock_0
MainSubsong0DisarkPointerRegionEnd10

MainSubsong0DisarkByteRegionStart11
    db 144    ; Duration.
MainSubsong0DisarkByteRegionEnd11
MainSubsong0DisarkPointerRegionStart12
    dw MainSubsong0_RegisterBlock_6
MainSubsong0DisarkPointerRegionEnd12

MainSubsong0_Track_3
MainSubsong0DisarkByteRegionStart13
    db 192    ; Duration.
MainSubsong0DisarkByteRegionEnd13
MainSubsong0DisarkPointerRegionStart14
    dw MainSubsong0_RegisterBlock_4
MainSubsong0DisarkPointerRegionEnd14

MainSubsong0_Track_4
MainSubsong0DisarkByteRegionStart15
    db 192    ; Duration.
MainSubsong0DisarkByteRegionEnd15
MainSubsong0DisarkPointerRegionStart16
    dw MainSubsong0_RegisterBlock_5
MainSubsong0DisarkPointerRegionEnd16

MainSubsong0_Track_5
MainSubsong0DisarkByteRegionStart17
    db 192    ; Duration.
MainSubsong0DisarkByteRegionEnd17
MainSubsong0DisarkPointerRegionStart18
    dw MainSubsong0_RegisterBlock_6
MainSubsong0DisarkPointerRegionEnd18


; The RegisterBlocks.
MainSubsong0DisarkByteRegionStart19
MainSubsong0_RegisterBlock_4
    db 121    ; Initial State: software only.
    db 188    ; Software period.
    db 3    ; Software period.

    db 57    ; Non-initial State, software only.

    db 53    ; Non-initial State, software only.

    db 49    ; Non-initial State, software only.

    db 45    ; Non-initial State, software only.

    db 41    ; Non-initial State, software only.

MainSubsong0_RegisterBlock_4_Loop
    db 57    ; Non-initial State, software only.

    db 53    ; Non-initial State, software only.

    db 49    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 8    ; Loop to index 6.
MainSubsong0DisarkPointerRegionStart20
    dw MainSubsong0_RegisterBlock_4_Loop
MainSubsong0DisarkPointerRegionEnd20

MainSubsong0_RegisterBlock_5
    db 121    ; Initial State: software only.
    db 123    ; Software period.
    db 1    ; Software period.

    db 8
MainSubsong0DisarkPointerRegionStart21
; Optimization: goto common Block at index 1.
    dw MainSubsong0_RegisterBlock_4 + 3
MainSubsong0DisarkPointerRegionEnd21
MainSubsong0_RegisterBlock_6
    db 131    ; Initial State : software and hardware.
    db 119    ; Software period.
    db 7    ; Software period.
    db 60    ; Hardware period.
    db 0    ; Hardware period.

MainSubsong0_RegisterBlock_6_Loop
    db 3    ; Non-initial State, software and hardware.

    db 8    ; Loop to index 1.
MainSubsong0DisarkPointerRegionStart22
    dw MainSubsong0_RegisterBlock_6_Loop
MainSubsong0DisarkPointerRegionEnd22

MainSubsong0_RegisterBlock_3
    db 131    ; Initial State : software and hardware.
    db 119    ; Software period.
    db 7    ; Software period.
    db 60    ; Hardware period.
    db 0    ; Hardware period.

    db 8
MainSubsong0DisarkPointerRegionStart23
; Optimization: goto common Block at index 1.
    dw MainSubsong0_RegisterBlock_6 + 5
MainSubsong0DisarkPointerRegionEnd23
MainSubsong0_RegisterBlock_0
    db 0    ; Initial State: no software, no hardware.

MainSubsong0_RegisterBlock_0_Loop
    db 4    ; Non-initial State, no software no hardware.

    db 8    ; Loop to index 1.
MainSubsong0DisarkPointerRegionStart24
    dw MainSubsong0_RegisterBlock_0_Loop
MainSubsong0DisarkPointerRegionEnd24

MainSubsong0_RegisterBlock_1
    db 121    ; Initial State: software only.
    db 222    ; Software period.
    db 1    ; Software period.

    db 8
MainSubsong0DisarkPointerRegionStart25
; Optimization: goto common Block at index 1.
    dw MainSubsong0_RegisterBlock_4 + 3
MainSubsong0DisarkPointerRegionEnd25
MainSubsong0DisarkByteRegionEnd19
