; Lo Pan's Attack, Linear RAW format V1.0.

; Generated by Arkos Tracker 3.

Main
MainDisarkGenerateExternalLabel

MainDisarkByteRegionStart0
Mainloop
    db 0    ; Command: data on channel index 0.
    db 48    ; Note (255 if absent).
    db 0    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 1    ; Command: data on channel index 1.
    db 82    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 2    ; Command: data on channel index 2.
    db 48    ; Note (255 if absent).
    db 0    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 77    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 80    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 77    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 65    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 77    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 80    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 82    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 77    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 80    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 77    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 61    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 60    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 82    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 2    ; Command: data on channel index 2.
    db 48    ; Note (255 if absent).
    db 0    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 0    ; Command: data on channel index 0.
    db 48    ; Note (255 if absent).
    db 0    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 1    ; Command: data on channel index 1.
    db 77    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 80    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 77    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 65    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 77    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 80    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 82    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 77    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 80    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 77    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 61    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 60    ; Note (255 if absent).
    db 3    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 48    ; Note (255 if absent).
    db 0    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 48    ; Note (255 if absent).
    db 0    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 16

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 48    ; Note (255 if absent).
    db 0    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 16

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 48    ; Note (255 if absent).
    db 0    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 16

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 73    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 70    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 68    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 48    ; Note (255 if absent).
    db 0    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 0    ; Command: data on channel index 0.
    db 66    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 65    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 48    ; Note (255 if absent).
    db 0    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 16

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 48    ; Note (255 if absent).
    db 0    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 16

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 48    ; Note (255 if absent).
    db 0    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 0    ; Command: data on channel index 0.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 16

    db 0    ; Command: data on channel index 0.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 73    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 70    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 68    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 48    ; Note (255 if absent).
    db 0    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 0    ; Command: data on channel index 0.
    db 66    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 65    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 0    ; Command: data on channel index 0.
    db 48    ; Note (255 if absent).
    db 0    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 66    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 81    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 81    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 80    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 58    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 58    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 86    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 86    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 58    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 66    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 81    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 81    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 80    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 58    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 58    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 86    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 86    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 58    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 66    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 81    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 81    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 80    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 58    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 58    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 86    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 86    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 58    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 5    ; Effect index.
    dw 3840    ; Effect value.
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 66    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 63    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 72    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 75    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 73    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 70    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 68    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 81    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 81    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 80    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 58    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 58    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 1    ; Command: data on channel index 1.
    db 86    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 86    ; Note (255 if absent).
    db 4    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 4

    db 1    ; Command: data on channel index 1.
    db 58    ; Note (255 if absent).
    db 5    ; Instrument (255 if absent).
    db 0    ; End of effects.

    db 254    ; Command: wait.
    dw 8

    db 253    ; Command: end.
MainDisarkWordForceReference1
    dw Mainloop    ; Loop here.
MainDisarkByteRegionEnd0
