; Events generated by Arkos Tracker 3.

MainEvents
MainEventsDisarkGenerateExternalLabel

MainDisarkByteRegionStart0
MainEvents_Loop
    dw 1    ; Wait for 0 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 20    ; Wait for 19 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 4

    dw 10    ; Wait for 9 frames.
    db 7

    dw 10    ; Wait for 9 frames.
    db 5

    dw 15    ; Wait for 14 frames.
    db 4

    dw 15    ; Wait for 14 frames.
    db 6

    dw 10    ; Wait for 9 frames.
    db 5

    dw 10    ; Wait for 9 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 5

    dw 5    ; Wait for 4 frames.
    db 0

    dw 0    ; End of sequence.
MainDisarkWordForceReference1
    dw MainEvents_Loop    ; Loops here.
MainDisarkByteRegionEnd0
