// File generated by CONVERT_PALETTE macro from CPCtelera
// Converted firmware palette declaration
// 
#ifndef _savagecolors_palette_H_
#define _savagecolors_palette_H_

#include <types.h>

extern const u8 savagecolors_palette[16];

#endif
